# Generated by Django 5.1.6 on 2025-02-25 04:42

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='longitude',
        ),
        migrations.AddField(
            model_name='landmark',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
