# Generated by Django 5.1.6 on 2025-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_landmark_latitude_remove_landmark_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
